# Generated by Django 3.2.8 on 2021-11-04 07:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teammate_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='anonymous', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/pic_2z37G75.png', upload_to='profile_pics'),
        ),
    ]
