# Generated by Django 3.2.8 on 2021-11-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate_finder_app', '0003_auto_20211104_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='anonymous', max_length=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
