# Generated by Django 3.2.8 on 2021-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate_finder_app', '0004_auto_20211104_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('All regions', 'All regions'), ('Brazil', 'Brazil'), ('Europe Nordic & East', 'Europe Nordic & East'), ('Europe West', 'Europe West'), ('North America', 'North America'), ('Latin America North', 'Latin America North'), ('Latin America South', 'Latin America South'), ('Oceania', 'Oceania'), ('Russia', 'Russia'), ('Turkey', 'Turkey')], default='anonymous', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
