# Generated by Django 3.2.8 on 2021-11-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate_finder_app', '0006_auto_20211104_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('cs_CZ', 'Czech'), ('el_GR', 'Greek'), ('pl_PL', 'Polish'), ('ro_RO', 'Romanian'), ('hu_HU', 'Hungarian'), ('en_GB', 'English (United Kingdom)'), ('de_DE', 'German'), ('es_ES', 'Spanish (Spain)'), ('es_AR', 'Spanish (Argentina)'), ('pt_BR', 'Portuguese (Brazil)'), ('en_US', 'English (United States)'), ('en_AU', 'English (Australia)'), ('ru_RU', 'Russian'), ('tr_TR', 'Turkish'), ('ms_MY', 'Malay'), ('en_PH', 'English (Republic of the Philippines)'), ('en_SG', 'English (Singapore)'), ('th_TH', 'Thai'), ('vn_VN', 'Vietnamese'), ('id_ID', 'Indonesian'), ('zh_MY', 'Chinese (Malaysia)'), ('zh_CN', 'Chinese (China)'), ('zh_TW', 'Chinese (Taiwan)')], max_length=15),
        ),
    ]
