# Generated by Django 3.2.8 on 2021-11-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate_finder_app', '0007_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('Iron', 'Iron'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master ', 'Master'), ('Grandmaster', 'Grandmaster'), ('Challenger', 'Challenger')], default='anonymous', max_length=11),
            preserve_default=False,
        ),
    ]
