# Generated by Django 3.2.8 on 2021-11-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate_finder_app', '0008_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.BooleanField(choices=[('Top', 'top')], default=False, max_length=10),
        ),
    ]
