# Generated by Django 3.2.8 on 2021-11-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate_finder_app', '0011_auto_20211105_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='text',
        ),
        migrations.AddField(
            model_name='profile',
            name='write',
            field=models.TextField(default='', verbose_name='Write something about yourself'),
            preserve_default=False,
        ),
    ]
