# Generated by Django 3.2.8 on 2021-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate_finder_app', '0012_auto_20211106_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('Czech', 'Czech'), ('Greek', 'Greek'), ('Polish', 'Polish'), ('Romanian', 'Romanian'), ('Hungarian', 'Hungarian'), ('English (United Kingdom)', 'English (United Kingdom)'), ('German', 'German'), ('Spanish (Spain)', 'Spanish (Spain)'), ('Spanish (Argentina)', 'Spanish (Argentina)'), ('Portuguese (Brazil', 'Portuguese (Brazil)'), ('English (United States)', 'English (United States)'), ('English (Australia)', 'English (Australia)'), ('Russian', 'Russian'), ('Turkish', 'Turkish'), ('Malay', 'Malay'), ('English (Republic of the Philippines)', 'English (Republic of the Philippines)'), ('English (Singapore)', 'English (Singapore)'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese'), ('Indonesian', 'Indonesian'), ('Chinese (Malaysia)', 'Chinese (Malaysia)'), ('Chinese (China)', 'Chinese (China)'), ('Chinese (Taiwan)', 'Chinese (Taiwan)')], max_length=37),
        ),
    ]
